# To release a build:
# example: git tag v0.2
# note: only lightweight tags work
# git push origin --tags
version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
artifacts:
  - path: MossApp\bin\Debug\MossApp.exe
    name: MossApp
deploy:
  release: MossApp-$(appveyor_repo_tag_name)
  description: 'MossApp $(appveyor_repo_tag_name) has been released.'
  provider: GitHub
  auth_token:
    secure: 5HkFvtU4gqVsm39KKO7EEfhQNwq7nB9FAxFGhxgEK1SjTKIPAYttvnj2IIt+wWYG
  artifact: MossApp
  draft: false
  prerelease: false
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
